CREATE TABLE `DAY_STATISTIC` (
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'The PK',
  `DAY` date NOT NULL COMMENT 'The day for the statistics.',
  `T_MIN` double NULL ,
  `T_MAX` double NULL ,
  `T_MED` double NULL ,
  `T0` double NULL ,
  `T1` double NULL ,
  `T2` double NULL ,
  `T3` double NULL ,
  `T4` double NULL ,
  `T5` double NULL ,
  `T6` double NULL ,
  `T7` double NULL ,
  `T8` double NULL ,
  `T9` double NULL ,
  `T10` double NULL ,
  `T11` double NULL ,
  `T12` double NULL ,
  `T13` double NULL ,
  `T14` double NULL ,
  `T15` double NULL ,
  `T16` double NULL ,
  `T17` double NULL ,
  `T18` double NULL ,
  `T19` double NULL ,
  `T20` double NULL ,
  `T21` double NULL ,
  `T22` double NULL ,
  `T23` double NULL ,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK1_DAY_STATISTIC` (`DAY`)
);